
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ListAssist.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ListItem
{

    public int Id { get; set; }

    public string Description { get; set; }

    public bool Done { get; set; }

    public int ListId { get; set; }



    public virtual List List { get; set; }

}

}
